# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMovie

pod 'SDWebImage', '~> 5.0'
pod 'IQKeyboardManager'
pod 'youtube-ios-player-helper'


end
